version: '2'
services:
  mysql-master:
    build:
      context: ./
      dockerfile: master/Dockerfile
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=replicas_db"
    links:
      - mysql-slave-1
      - mysql-slave-2
    ports:
      - "33065:3306"
    restart: always
    hostname: mysql-master
  mysql-slave-1:
    build:
      context: ./
      dockerfile: slave1/Dockerfile
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=replicas_db"
    ports:
      - "33066:3306"
    restart: always
    hostname: mysql-slave1
  mysql-slave-2:
    build:
      context: ./
      dockerfile: slave2/Dockerfile
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=replicas_db"
    ports:
      - "33067:3306"
    restart: always
    hostname: mysql-slave2
