package com.hecheng.entity.resp;

import lombok.Data;

import java.io.Serializable;

@Data
public class GroupInfoResp implements Serializable{
	
    /**
	 * 
	 */
	private static final long serialVersionUID = -7432890422297315865L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_GROUP_INFO.GRP_ID
     *
     * @mbg.generated Mon May 14 11:00:19 CST 2018
     */
    private String grpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_GROUP_INFO.GRP_CNAME
     *
     * @mbg.generated Mon May 14 11:00:19 CST 2018
     */
    private String grpCname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_GROUP_INFO.GRP_ENAME
     *
     * @mbg.generated Mon May 14 11:00:19 CST 2018
     */
    private String grpEname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_GROUP_INFO.GRP_LEVEL
     *
     * @mbg.generated Mon May 14 11:00:19 CST 2018
     */
    private String grpLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_GROUP_INFO.GRP_REMARK
     *
     * @mbg.generated Mon May 14 11:00:19 CST 2018
     */
    private String grpRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_GROUP_INFO.CORE_RIGHT
     *
     * @mbg.generated Mon May 14 11:00:19 CST 2018
     */
    private String coreRight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_GROUP_INFO.OPERATOR_CODE
     *
     * @mbg.generated Mon May 14 11:00:19 CST 2018
     */
    private String operatorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_GROUP_INFO.UPDATE_DATE
     *
     * @mbg.generated Mon May 14 11:00:19 CST 2018
     */
    private String updateDate;

}