package com.hecheng.entity.resp;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

@Data
public class UserInfoResp implements Serializable{
	
    /**
	 * 
	 */
	private static final long serialVersionUID = 2439349845976256758L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER_INFO.WORK_ID
     *
     * @mbg.generated Mon May 14 11:00:19 CST 2018
     */
    private String workId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER_INFO.USER_LOGIN_NAME
     *
     * @mbg.generated Mon May 14 11:00:19 CST 2018
     */
    private String userLoginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER_INFO.USER_BANK_CODE
     *
     * @mbg.generated Mon May 14 11:00:19 CST 2018
     */
    private String userBankCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER_INFO.USER_DEPT
     *
     * @mbg.generated Mon May 14 11:00:19 CST 2018
     */
    private String userDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER_INFO.USER_NAME
     *
     * @mbg.generated Mon May 14 11:00:19 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER_INFO.USER_PWD
     *
     * @mbg.generated Mon May 14 11:00:19 CST 2018
     */
    private String userPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER_INFO.USER_LEVEL
     *
     * @mbg.generated Mon May 14 11:00:19 CST 2018
     */
    private String userLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER_INFO.USER_CHK_CODE
     *
     * @mbg.generated Mon May 14 11:00:19 CST 2018
     */
    private String userChkCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER_INFO.USER_REMARK
     *
     * @mbg.generated Mon May 14 11:00:19 CST 2018
     */
    private String userRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER_INFO.USER_STATUS
     *
     * @mbg.generated Mon May 14 11:00:19 CST 2018
     */
    private String userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER_INFO.USER_CDATE
     *
     * @mbg.generated Mon May 14 11:00:19 CST 2018
     */
    private Date userCdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER_INFO.USER_DEL_TIME
     *
     * @mbg.generated Mon May 14 11:00:19 CST 2018
     */
    private Date userDelTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER_INFO.OPERATOR_CODE
     *
     * @mbg.generated Mon May 14 11:00:19 CST 2018
     */
    private String operatorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER_INFO.UPDATE_DATE
     *
     * @mbg.generated Mon May 14 11:00:19 CST 2018
     */
    private String updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER_INFO.TELEPHONE
     *
     * @mbg.generated Mon May 14 11:00:19 CST 2018
     */
    private String telephone;

    /**
     * 用户所属组列表(即用户角色)
     */
    private List<GroupInfoResp> groupInfos;
    
}
